### ISSUE TITLE
How did you do to run the testsrvr.lua successful?

### ISSUE THREAD

**Issue by Think-Jumper** [BixData/gluasocket#7]
How did you do to run the testsrvr.lua successful? When I run this lua file, it shows the error:```socket.dns.getaddrinfo(address) not implemented yet```    

By the way, you do the good job to write this luasocket library in golang,it very useful.

**Comment by drauschenbach** [comment]
Thanks! Glad you are able to make use of the library and support it through your bug reports!

I filled a few gaps (above). Let me know if they help you towards your goal of getting `testsrv.lua` to run in your environment.

**Comment by Think-Jumper** [comment]
I use your library to connect my other remote server by the socket for testing, but there always something weird. So I find the ```testsrv.lua``` for testing my environment. Because I think these lua files must be tested and verified by yourself.  I just run the ```testsrv.lua``` to confirm if is my environment or my other code written had something wrong.As you konw, I found it.

**Comment by drauschenbach** [comment]
I've only ever used my library as a socket client. So the socket server functionality was not implemented yet. You're the first. :-)

**Comment by Think-Jumper** [comment]
Finally, I get the inspiration which gives by your code. I've wrap the golang's socket to call by lua and achieve the goal of receiving data asynchronous in lua code. Now I can create many sockets in lua code and receive data in different goroutine.

**Comment by drauschenbach** [comment]
Excellent!
